[package]
name = "fanova"
version = "0.1.0"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ordered-float = "1"
rand = "0.7"
rayon = "1"
thiserror = "1"

[dev-dependencies]
anyhow = "1"
